/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.login.view;

/**
 *
 * @author kennedy
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaLogin = new javax.swing.JPanel();
        LogoUser = new javax.swing.JLabel();
        lblProjName = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnEnter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        linkRegister = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMostrarPassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMostrarLogin = new javax.swing.JLabel();
        TelaCadastrousuario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SelectGen = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TelaLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/login/imagens/usuario2.png"))); // NOI18N
        TelaLogin.add(LogoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, -1));

        lblProjName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProjName.setText("Sistema De Vendas");
        TelaLogin.add(lblProjName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLogin.setText("Login:");
        TelaLogin.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 37, -1));
        TelaLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 309, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Senha:");
        TelaLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        TelaLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 311, -1));

        btnEnter.setText("ENTRAR");
        btnEnter.addActionListener(this::btnEnterActionPerformed);
        TelaLogin.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nao tenho conta?");
        TelaLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 520, -1));

        linkRegister.setForeground(new java.awt.Color(51, 51, 255));
        linkRegister.setText("Cadastre-se");
        linkRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkRegisterMouseClicked(evt);
            }
        });
        TelaLogin.add(linkRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 70, 20));
        TelaLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 375, 88, -1));

        txtMostrarPassword.setText(" ");
        TelaLogin.add(txtMostrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 375, 106, -1));
        TelaLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 347, 88, -1));

        txtMostrarLogin.setText(" ");
        TelaLogin.add(txtMostrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 347, 106, -1));

        getContentPane().add(TelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TelaCadastrousuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nome completo:");
        TelaCadastrousuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 41, 111, -1));

        jLabel10.setText("CPF:");
        TelaCadastrousuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 43, -1));

        jLabel11.setText("Genero:");
        TelaCadastrousuario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 43, -1));

        jLabel12.setText("Data de Nascimento:");
        TelaCadastrousuario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        SelectGen.setEditable(true);
        SelectGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outros" }));
        SelectGen.setToolTipText("");
        SelectGen.addActionListener(this::SelectGenActionPerformed);
        TelaCadastrousuario.add(SelectGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 124, -1));
        TelaCadastrousuario.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 120, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TelaCadastrousuario.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 120, -1));

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setToolTipText("");
        TelaCadastrousuario.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, -1));

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TelaCadastrousuario.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        TelaCadastrousuario.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 120, -1));
        TelaCadastrousuario.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 120, -1));
        TelaCadastrousuario.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 120, -1));
        TelaCadastrousuario.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));

        jLabel13.setText("Telefone:");
        TelaCadastrousuario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel14.setText("Email:");
        TelaCadastrousuario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel15.setText("Login:");
        TelaCadastrousuario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel16.setText("Senha:");
        TelaCadastrousuario.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel17.setText("Confirmar Senha:");
        TelaCadastrousuario.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        TelaCadastrousuario.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Confirmar");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        TelaCadastrousuario.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        getContentPane().add(TelaCadastrousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        String LoginDigitado = txtLogin.getText();
        String PasswordDigitado = new String(txtPassword.getPassword());
        
        txtMostrarLogin.setText(LoginDigitado);
        txtMostrarPassword.setText(PasswordDigitado);
        jLabel4.setText("Login Digitado:");
        jLabel5.setText("Senha Digitada:");
    }//GEN-LAST:event_btnEnterActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    //Link para tela de cadastro
    private void linkRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkRegisterMouseClicked
        // TODO add your handling code here:
        TelaLogin.setVisible(false);
        TelaCadastrousuario.setVisible(true);
    }//GEN-LAST:event_linkRegisterMouseClicked

    private void SelectGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectGenActionPerformed
    // botao csncelsr para voltar para tela de login
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TelaCadastrousuario.setVisible(false);
        TelaLogin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoUser;
    private javax.swing.JComboBox<String> SelectGen;
    private javax.swing.JPanel TelaCadastrousuario;
    private javax.swing.JPanel TelaLogin;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProjName;
    private javax.swing.JLabel linkRegister;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JLabel txtMostrarLogin;
    private javax.swing.JLabel txtMostrarPassword;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
