/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.login.view;

/**
 *
 * @author kennedy
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        TelaCadastrousuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaLogin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtMostrarPassword = new javax.swing.JLabel();
        txtMostrarLogin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        TelaCadastrousuario = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TelaLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Cadastre-se");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        TelaLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 70, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nao tenho conta?");
        TelaLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 520, -1));

        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        TelaLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 311, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/login/imagens/usuario2.png"))); // NOI18N
        TelaLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, -1));

        txtMostrarPassword.setText(" ");
        TelaLogin.add(txtMostrarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 375, 106, -1));

        txtMostrarLogin.setText(" ");
        TelaLogin.add(txtMostrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 347, 106, -1));
        TelaLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 375, 88, -1));
        TelaLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 347, 88, -1));

        jButton1.setText("ENTRAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        TelaLogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Senha:");
        TelaLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Login:");
        TelaLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 37, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Sistema De Vendas");
        TelaLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        TelaLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 309, -1));

        getContentPane().add(TelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setText("teste");

        javax.swing.GroupLayout TelaCadastrousuarioLayout = new javax.swing.GroupLayout(TelaCadastrousuario);
        TelaCadastrousuario.setLayout(TelaCadastrousuarioLayout);
        TelaCadastrousuarioLayout.setHorizontalGroup(
            TelaCadastrousuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastrousuarioLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel9)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        TelaCadastrousuarioLayout.setVerticalGroup(
            TelaCadastrousuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaCadastrousuarioLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel9)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        getContentPane().add(TelaCadastrousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String LoginDigitado = txtLogin.getText();
        String PasswordDigitado = new String(txtPassword.getPassword());
        
        txtMostrarLogin.setText(LoginDigitado);
        txtMostrarPassword.setText(PasswordDigitado);
        jLabel4.setText("Login Digitado:");
        jLabel5.setText("Senha Digitada:");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jLabel6.setText("Certo");
        TelaLogin.setVisible(false);
        TelaCadastrousuario.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TelaCadastrousuario;
    private javax.swing.JPanel TelaLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JLabel txtMostrarLogin;
    private javax.swing.JLabel txtMostrarPassword;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
